---
- name: Installing Complete Java
  hosts: ws
  gather_facts: false
  become: true
  tasks:
  - name: Update APT Package Manager repositories cache
    become: true
    apt:
      update_cache: yes

  - name: Install Java(JRE+JDK)
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      openjdk-8-jdk
